services:
  nest-app:
    build: .
    container_name: nest_app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      DB_HOST: sebastian-sql-server-2026.database.windows.net
      DB_PORT: 1433
      DB_USER: sqladmin
      DB_PASSWORD: 'TuPassword123!'
      DB_NAME: AdventureWorks2
      DB_ENCRYPT: 'true'
      DB_TRUST_CERT: 'false'
      JWT_SECRET: ${JWT_SECRET}
